# Solarized Theme (Dark)

[colors]
bg = "48;2;0;43;54"
fg = "22;24;38;2;238;232;213"
err = "1;166"
s_wayland = "38;2;42;161;152"
s_xorg = "38;2;181;137;0"
s_shell = "244"
e_hostname = "241"
e_date = "38;2;65;133;153"
e_box = "38;2;253;246;227"
e_header = "1;4;160"
e_user = "38;5;33"
e_passwd = "4;2;203;75;22"
e_badpasswd = "3;4;160"
e_key = "33"

[behavior]
# include_defshell = true
timefmt = "%Y-%m-%d %H:%M:%S"
# refresh_rate = 100
source = "/etc/lidm.env"
source = "/etc/locale.conf"
user_source = ".lidm.env"
